version: "3.7"

services:
  mydb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty
    volumes:
      - ./.db-data:/var/lib/postgresql/data
    ports:
      - 5434:5432

  app:
    container_name: "pdf-generator-server"
    build: .
    depends_on:
      - mydb
    restart: always
    environment:
      DB_HOST: mydb
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: qwerty
      DB_NAME: postgres
      JWT_SECRET: secret
    ports:
      - "8080:3000"
    working_dir: /home/node/app
    volumes:
      - "./:/home/node/app"
    command: bash -c "npm i && npm run start:dev"
