version: '3.7'

services:
  app:
    container_name: 'pdf-generator-server'
    build: .
    restart: always
    ports:
      - '8080:3000'
    working_dir: /home/node/app
    volumes:
      - './:/home/node/app'
    command: bash -c 'npm i && npm run start:dev'
